# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :mac do
  desc "Test CI MacOS"
  lane :test_ci_macos do
    scan(
      project:"EssentialFeed/EssentialFeed.xcodeproj",
      scheme: "CI_macOS",
      clean: true
      )
  end
end

platform :ios do
  desc "Test CI iOS"
  lane :test_ci_ios do
    scan(
      workspace:"EssentialApp.xcworkspace",
      scheme: "CI_iOS",
      device: "iPhone 15 Pro Max",
      clean: true
      )
  end
end