# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :mac do
  desc "Test CI MacOS"
  lane :test_ci_macos do
    scan(
      project:"EssentialFeed/EssentialFeed.xcodeproj",
      scheme: "CI_macOS",
      clean: true
      )
  end
end

platform :ios do
  desc "Test CI iOS"
  lane :test_ci_ios do
    scan(
      workspace:"EssentialApp.xcworkspace",
      scheme: "CI_iOS",
      device: "iPhone 15 Pro Max",
      clean: true
      )
  end

  desc "Deploy to Testflight"
  lane :deploy_testflight do
    increment_build_number(
      build_number: ENV['GITHUB_RUN_NUMBER'],
      xcodeproj: "EssentialApp/EssentialApp.xcodeproj"
      )
    build_app(
      scheme: "EssentialApp", 
      export_method: "app-store",
      export_options: ".github/deployment/ExportOptions.plist",
      workspace: "EssentialApp.xcworkspace", 
      include_bitcode: false
      )
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_filepath: ".github/deployment/ASC_AuthKey.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
  )
    upload_to_testflight(
      skip_submission: true,
      api_key: api_key
      )
  end
end