name: CI-iOS

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.2'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bundle Install
        run: bundle install
      - name: Test CI iOS
        run: 
          bundle exec fastlane ios test_ci_ios