name: EssentialFeed Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: End-to-End Test EssentialFeed Framework
    runs-on: macos-13

    steps:
      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.2'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bundle Install
        run: bundle install
      - name: Test CI MacOS
        run:
          bundle exec fastlane mac test_ci_macos
      - name: Test CI iOS
        run: 
          bundle exec fastlane ios test_ci_ios