name: EssentialFeed Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: End-to-End Test EssentialFeed Framework
    runs-on: macos-13

    steps:
      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.0.1'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        env:
          scheme: CI
        run: |
          xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "$scheme" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
